json.(order, :id,
			 :design_approval,
			 :unit, :tooth_material,
			 :design_type,
			 :turn_around_time,
			 :model,
			 :custom_tray,
			 :rpd_framework,
			 :abutment_optional,
			 :message,
			 :destination,
			 :document_url,
			 :stl_file_url,
			 :tooth_no,
			 :status,
			 :updated_at,
			 :created_at)